import turtle
tia = turtle.Turtle()
tia.pensize(10)
tia.color("red")
tia.forward(200)
tia.left(90)
tia.color("green")
tia.forward(200)
tia.left(90)
tia.color("yellow")
tia.forward(200)
tia.left(90)
tia.color("blue")
tia.forward(200)
